Ephemeral ports sanity check
tuenti/kube2lb pull request #17
Opened 2017-08-03 17:15 UTC by dannyk81

* Collect the range values from `net.ipv4.ip_local_port_range` sysctl parameter
* If above is successful, all service ports of each service are checked to ensure they do not fall into this range
* Services that define a service port (at least one) with the range will be skipped and not configured

2017-08-03 17:54 UTC, jsoriano requested changes
Thanks!

2017-08-03 17:54 UTC, jsoriano commented on kubernetes.go
> +			if found {
As you are not using `found` later and is a simple condition you could put it directly in the if (`if InEphemeralPortsRange(s.Spec.Ports) {...}`)

2017-08-03 17:54 UTC, jsoriano commented on sanitychecks.go
> +Copyright 2016 Tuenti Technologies S.L. All rights reserved.
2017 :)

2017-08-03 17:54 UTC, jsoriano commented on sanitychecks.go
> +        "github.com/achanda/go-sysctl"
Vendorize the dependency (https://github.com/tools/godep#add-a-dependency)

2017-08-03 17:54 UTC, jsoriano commented on sanitychecks.go
> +        r, err := sysctl.Get("net.ipv4.ip_local_port_range")
This can also be read from `/proc/sys/net/ipv4/ip_local_port_range` in case you don't want to add a new dependency.

2017-08-03 17:54 UTC, jsoriano commented on sanitychecks.go
> +                return &EphemeralPortsRange{check: false, LowPort: 0, HighPort: 0}
Indentation? Look for how to hook [`go fmt`](https://blog.golang.org/go-fmt-your-code) with your IDE. And take a look also to `go vet`.

2017-08-03 17:54 UTC, jsoriano commented on sanitychecks.go
> +		return false
Not needed

2017-08-03 17:54 UTC, jsoriano commented on sanitychecks.go
> +		for _, port := range ports {
To have one less nesting level in the main part of the function you could return in the if:
```
if !ephemeralPortsRange.check {
    return false
}
for _, port := range ports {
....
}
return false
```

2017-08-03 17:54 UTC, jsoriano commented on sanitychecks.go
> +}
You could define a method like  for this struct with the logic to check if a Range contains a port, so you could write checks like:
```
port := 2048
r := EphemeralPortsRange{check: true, LowPort: 1024, HighPort; 32000}
if r.Contains(port) {
    panic()
}

2017-08-03 17:54 UTC, jsoriano commented on sanitychecks.go
> +	h,_ := strconv.Atoi(strings.Fields(r)[1])
Other option to parse this:
```
	var l, h int32
	fmt.Sscanf(r, "%d %d", &l, &h)
	return &EphemeralPortsRange{check: true, LowPort: l, HighPort: h}
```

2017-08-03 17:54 UTC, jsoriano commented on sanitychecks.go
> +// Retrieve the data from sysctl and return the values, disable the check if unseccseful and log
typo? (unseccseful)

2017-08-03 17:54 UTC, jsoriano commented on kubernetes.go
> +				log.Printf("Service %s in %s has a Service Port within the ephemral ports range (%d - %d), skipping it. Please check your configuration!.", s.Name, s.Namespace, ephemeralPortsRange.LowPort, ephem
`EphemeralPortsRange` could have a String() method to make this line shorter :)

2017-08-03 18:03 UTC, jsoriano commented on sanitychecks.go
> +        r, err := sysctl.Get("net.ipv4.ip_local_port_range")
(but it's ok if you add it :))

2017-08-03 18:21 UTC, dannyk81 commented on sanitychecks.go
> +Copyright 2016 Tuenti Technologies S.L. All rights reserved.
copy/paste ;-) would you like me to update in all files?

2017-08-03 18:21 UTC, dannyk81 commented on kubernetes.go
> +			if found {
done, old habits... hard to kill ;)

2017-08-03 18:23 UTC, dannyk81 commented on sanitychecks.go
> +        "github.com/achanda/go-sysctl"
done!

2017-08-03 18:24 UTC, dannyk81 commented on sanitychecks.go
> +// Retrieve the data from sysctl and return the values, disable the check if unseccseful and log
yea... this word eludes me - fixed.

2017-08-03 18:25 UTC, dannyk81 commented on sanitychecks.go
> +        r, err := sysctl.Get("net.ipv4.ip_local_port_range")
I know (in fact it's what the package is doing)... I'll keep it if you don't mind.

2017-08-03 18:27 UTC, dannyk81 commented on sanitychecks.go
> +                return &EphemeralPortsRange{check: false, LowPort: 0, HighPort: 0}
mmm, strange! I see now it's not properly set... will adjust!

2017-08-03 18:30 UTC, dannyk81 commented on sanitychecks.go
> +	h,_ := strconv.Atoi(strings.Fields(r)[1])
This is nice! and no need for strings and strconv

2017-08-03 18:35 UTC, dannyk81 commented on sanitychecks.go
> +		for _, port := range ports {
👍

2017-08-03 18:35 UTC, dannyk81 commented on sanitychecks.go
> +		return false
indeed

2017-08-03 18:46 UTC, jsoriano commented on sanitychecks.go
> +Copyright 2016 Tuenti Technologies S.L. All rights reserved.
Asa you wish :)

2017-08-03 19:12 UTC, dannyk81 commented on sanitychecks.go
> +}
logic moved to a method 👍

2017-08-03 19:13 UTC, dannyk81 commented on kubernetes.go
> +				log.Printf("Service %s in %s has a Service Port within the ephemral ports range (%d - %d), skipping it. Please check your configuration!.", s.Name, s.Namespace, ephemeralPortsRange.LowPort, ephem
Yea ;-) now the long line is somewhere else, hehe

2017-08-03 19:30 UTC, dannyk81 commented on sanitychecks.go
> +Copyright 2016 Tuenti Technologies S.L. All rights reserved.
Changed in the files I touched...

2017-08-03 19:56 UTC, jsoriano commented on kubernetes.go
> +				log.Printf("Service %s in %s has a Service Port within the ephemral ports range (%s), skipping it. Please check your configuration!.", s.Name, s.Namespace, ephemeralPortsRange.String())
No need to call `String()`, now your object implements the [`Stringer`](https://golang.org/pkg/fmt/#Stringer) interface :)

2017-08-03 19:56 UTC, jsoriano commented on sanitychecks.go
> +		log.Fatalf("Error reading from sysctl: %s, ephemeral ports range checks will be skipped", err)
Fatalf is like Print and os.Exit(-1), I don't think we want to end here :) use just Print.

2017-08-03 19:56 UTC, jsoriano commented on sanitychecks.go
> +Copyright 2016 Tuenti Technologies S.L. All rights reserved.
Perfect

2017-08-03 20:19 UTC, dannyk81 commented on sanitychecks.go
> +		log.Fatalf("Error reading from sysctl: %s, ephemeral ports range checks will be skipped", err)
Oyyy.... I forgot to change it back when we agreed to make it "relaxed"

2017-08-03 20:24 UTC, dannyk81 commented on kubernetes.go
> +				log.Printf("Service %s in %s has a Service Port within the ephemral ports range (%s), skipping it. Please check your configuration!.", s.Name, s.Namespace, ephemeralPortsRange.String())
Sweeeeet! done ;-)

2017-08-03 20:26 UTC, jsoriano commented
I think everything looks good :) @dannyk81 would you like to squash the commits before merging?

2017-08-03 20:33 UTC, jsoriano commented
Oh, and btw, it'd be awesome if you could do some simple tests for this.

2017-08-03 20:38 UTC, dannyk81 commented
Sounds good, let me work out something quickly.

2017-08-04 08:48 UTC, jsoriano commented on sanitychecks.go
> +func (r EphemeralPortsRange) InRange(ports []v1.ServicePort) bool {
Now that this method belongs to `EphemeralPortsRange` I see a bit of duplication with the method `Contains`, WDYT?

2017-08-04 08:48 UTC, jsoriano commented on sanitychecks_test.go
> +/*
Great :)

2017-08-04 08:49 UTC, jsoriano commented on sanitychecks.go
> +func (r EphemeralPortsRange) InRange(ports []v1.ServicePort) bool {
I'd also prefer the method to be a verb, what about someething like `ContainsAnyServicePort`?

2017-08-04 08:59 UTC, jsoriano commented on sanitychecks.go
> +func (r EphemeralPortsRange) InRange(ports []v1.ServicePort) bool {
Ooor, thinking that we might have more checks in the future, we could even have an interface like this one:
```
type ServiceValidator interface {
    ValidateService(*v1.Service) bool
}
```
And this method would be the implementation for `EphemeralPortsRange`.

2017-08-04 11:58 UTC, dannyk81 commented on sanitychecks.go
> +func (r EphemeralPortsRange) InRange(ports []v1.ServicePort) bool {
I agree about the duplicate methods between InRange & Contains, this came to me at late hour yesterday but was too tired to do something about it ;-)

We can go for the verb, for me true/false methods are always natural in form of a question (InRange? Contains?) but `ContainsAnyServicePort` is informative and clear, let's go for it!

Interface sounds like a solid approach to make this more extendable, let me work in this 👍

2017-08-05 12:33 UTC, jsoriano approved these changes

2017-08-05 12:34 UTC, merged